import type { Metadata } from "next";
import { Inter, Noto_Sans } from "next/font/google";
import "./globals.scss";
import LayoutClient from "./layout.client";

// Импортируем шрифты
const inter = Inter({ subsets: ["latin"] });
const notoSans = Noto_Sans({ subsets: ["latin", "cyrillic"] }); // Добавляем латинский и кириллический

export const metadata: Metadata = {
  title: "Экспериментальная гимназия №3",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${notoSans.className}`}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
